project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://babissimo.github.io
  title: "Babissimo"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Babissimo
      - icon: linkedin
        href: https://linkedin.com/in/alexandercharters
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
open-graph: true



